<?php
include_once("../scripts/check.php");
include_once('../scripts/head.php');
/**
 * Created by PhpStorm.
 * User: Roman
 * Date: 28.02.16
 * Time: 19:36
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Неправильные глаголы</title>
    <link rel="stylesheet" href="/css/commonStylesheet.css">
</head>
<body>
<div class="feed">
    <h1>
        Неправильные английские глаголы. Таблица неправильных глаголов английского языка.
    </h1>
    <article>
        В отличие от большинства глаголов английского языка, неправильные английские глаголы образуют формы прошедшего
        неопределенного времени и причастия прошедшего времени особым образом. Выделяют несколько основных способов их
        образования, которые, тем не менее, не описывают все возможные случаи. Изучить все неправильные глаголы
        английского языка возможно путем их непосредственного запоминания.<br><br>
    </article>

    <h2>
        Таблица неправильных глаголов английского языка
    </h2>
    <article>
        В приведенной ниже таблице в алфавитном порядке собраны 100 наиболее употребляемых неправильных глаголов
        английского языка.<br><br>
    </article>
    <table>
        <tr>
            <th style="width: 20%">
                Infinitive
            </th>
            <th style="width: 20%">
                Past Simple
            </th>
            <th style="width: 20%">
                Past Participle
            </th>
            <th>
                Перевод
            </th>
        </tr>
        <tr>
            <td>
                be
            </td>
            <td>
                was, were
            </td>
            <td>
                been
            </td>
            <td>
                <span>быть, являться</span></td>
        </tr>
        <tr>
            <td>
                beat
            </td>
            <td>
                beat
            </td>
            <td>
                beaten
            </td>
            <td>
                <span>бить, колотить</span></td>
        </tr>
        <tr>
            <td>
                become
            </td>
            <td>
                became
            </td>
            <td>
                become
            </td>
            <td>
                <span>становиться</span></td>
        </tr>
        <tr>
            <td>
                begin
            </td>
            <td>
                began
            </td>
            <td>
                begun
            </td>
            <td>
                <span>начинать</span></td>
        </tr>
        <tr>
            <td>
                bend
            </td>
            <td>
                bent
            </td>
            <td>
                bent
            </td>
            <td>
                <span>гнуть</span></td>
        </tr>
        <tr>
            <td>
                bet
            </td>
            <td>
                bet
            </td>
            <td>
                bet
            </td>
            <td>
                <span>держать пари</span></td>
        </tr>
        <tr>
            <td>
                bite
            </td>
            <td>
                bit
            </td>
            <td>
                bitten
            </td>
            <td>
                <span>кусать</span></td>
        </tr>
        <tr>
            <td>
                blow
            </td>
            <td>
                blew
            </td>
            <td>
                blown
            </td>
            <td>
                <span>дуть, выдыхать</span></td>
        </tr>
        <tr>
            <td>
                break
            </td>
            <td>
                broke
            </td>
            <td>
                broken
            </td>
            <td>
                <span>ломать, разбивать, разрушать</span></td>
        </tr>
        <tr>
            <td>
                bring
            </td>
            <td>
                brought
            </td>
            <td>
                brought
            </td>
            <td>
                <span>приносить, привозить, доставлять</span></td>
        </tr>
        <tr>
            <td>
                build
            </td>
            <td>
                built
            </td>
            <td>
                built
            </td>
            <td>
                <span>строить, сооружать</span></td>
        </tr>
        <tr>
            <td>
                buy
            </td>
            <td>
                bought
            </td>
            <td>
                bought
            </td>
            <td>
                <span>покупать, приобретать</span></td>
        </tr>
        <tr>
            <td>
                catch
            </td>
            <td>
                caught
            </td>
            <td>
                caught
            </td>
            <td>
                <span>ловить, поймать, схватить</span></td>
        </tr>
        <tr>
            <td>
                choose
            </td>
            <td>
                chose
            </td>
            <td>
                chosen
            </td>
            <td>
                <span>выбирать, избирать</span></td>
        </tr>
        <tr>
            <td>
                come
            </td>
            <td>
                came
            </td>
            <td>
                come
            </td>
            <td>
                <span>приходить, подходить</span></td>
        </tr>
        <tr>
            <td>
                cost
            </td>
            <td>
                cost
            </td>
            <td>
                cost
            </td>
            <td>
                <span>стоить, обходиться</span></td>
        </tr>
        <tr>
            <td>
                cut
            </td>
            <td>
                cut
            </td>
            <td>
                cut
            </td>
            <td>
                <span>резать, разрезать</span></td>
        </tr>
        <tr>
            <td>
                deal
            </td>
            <td>
                dealt
            </td>
            <td>
                dealt
            </td>
            <td>
                <span>иметь дело, распределять</span></td>
        </tr>
        <tr>
            <td>
                dig
            </td>
            <td>
                dug
            </td>
            <td>
                dug
            </td>
            <td>
                <span>копать, рыть</span></td>
        </tr>
        <tr>
            <td>
                do
            </td>
            <td>
                did
            </td>
            <td>
                done
            </td>
            <td>
                <span>делать, выполнять</span></td>
        </tr>
        <tr>
            <td>
                draw
            </td>
            <td>
                drew
            </td>
            <td>
                drawn
            </td>
            <td>
                <span>рисовать, чертить</span></td>
        </tr>
        <tr>
            <td>
                drink
            </td>
            <td>
                drank
            </td>
            <td>
                drunk
            </td>
            <td>
                <span>пить</span></td>
        </tr>
        <tr>
            <td>
                drive
            </td>
            <td>
                drove
            </td>
            <td>
                driven
            </td>
            <td>
                <span>ездить, подвозить</span></td>
        </tr>
        <tr>
            <td>
                eat
            </td>
            <td>
                ate
            </td>
            <td>
                eaten
            </td>
            <td>
                <span>есть, поглощать, поедать</span></td>
        </tr>
        <tr>
            <td>
                fall
            </td>
            <td>
                fell
            </td>
            <td>
                fallen
            </td>
            <td>
                <span>падать</span></td>
        </tr>
        <tr>
            <td>
                feed
            </td>
            <td>
                fed
            </td>
            <td>
                fed
            </td>
            <td>
                <span>кормить</span></td>
        </tr>
        <tr>
            <td>
                feel
            </td>
            <td>
                felt
            </td>
            <td>
                felt
            </td>
            <td>
                <span>чувствовать, ощущать</span></td>
        </tr>
        <tr>
            <td>
                fight
            </td>
            <td>
                fought
            </td>
            <td>
                fought
            </td>
            <td>
                <span>драться, сражаться, воевать</span></td>
        </tr>
        <tr>
            <td>
                find
            </td>
            <td>
                found
            </td>
            <td>
                found
            </td>
            <td>
                <span>находить, обнаруживать</span></td>
        </tr>
        <tr>
            <td>
                fly
            </td>
            <td>
                flew
            </td>
            <td>
                flown
            </td>
            <td>
                <span>летать</span></td>
        </tr>
        <tr>
            <td>
                forget
            </td>
            <td>
                forgot
            </td>
            <td>
                forgotten
            </td>
            <td>
                <span>забывать о (чём-либо)</span></td>
        </tr>
        <tr>
            <td>
                forgive
            </td>
            <td>
                forgave
            </td>
            <td>
                forgiven
            </td>
            <td>
                <span>прощать</span></td>
        </tr>
        <tr>
            <td>
                freeze
            </td>
            <td>
                froze
            </td>
            <td>
                frozen
            </td>
            <td>
                <span>замерзать, замирать</span></td>
        </tr>
        <tr>
            <td>
                get
            </td>
            <td>
                got
            </td>
            <td>
                got
            </td>
            <td>
                <span>получать, добираться</span></td>
        </tr>
        <tr>
            <td>
                give
            </td>
            <td>
                gave
            </td>
            <td>
                given
            </td>
            <td>
                <span>дать, подать, дарить</span></td>
        </tr>
        <tr>
            <td>
                go
            </td>
            <td>
                went
            </td>
            <td>
                gone
            </td>
            <td>
                <span>идти, двигаться</span></td>
        </tr>
        <tr>
            <td>
                grow
            </td>
            <td>
                grew
            </td>
            <td>
                grown
            </td>
            <td>
                <span>расти, вырастать</span></td>
        </tr>
        <tr>
            <td>
                hang
            </td>
            <td>
                hung
            </td>
            <td>
                hung
            </td>
            <td>
                <span>вешать, развешивать, висеть</span></td>
        </tr>
        <tr>
            <td>
                have
            </td>
            <td>
                had
            </td>
            <td>
                had
            </td>
            <td>
                <span>иметь, обладать</span></td>
        </tr>
        <tr>
            <td>
                hear
            </td>
            <td>
                heard
            </td>
            <td>
                heard
            </td>
            <td>
                <span>слышать, услышать</span></td>
        </tr>
        <tr>
            <td>
                hide
            </td>
            <td>
                hid
            </td>
            <td>
                hidden
            </td>
            <td>
                <span>прятать, скрывать</span></td>
        </tr>
        <tr>
            <td>
                hit
            </td>
            <td>
                hit
            </td>
            <td>
                hit
            </td>
            <td>
                <span>ударять, поражать</span></td>
        </tr>
        <tr>
            <td>
                hold
            </td>
            <td>
                held
            </td>
            <td>
                held
            </td>
            <td>
                <span>держать, удерживать, задерживать</span></td>
        </tr>
        <tr>
            <td>
                hurt
            </td>
            <td>
                hurt
            </td>
            <td>
                hurt
            </td>
            <td>
                <span>ранить, причинять боль, ушибить</span></td>
        </tr>
        <tr>
            <td>
                keep
            </td>
            <td>
                kept
            </td>
            <td>
                kept
            </td>
            <td>
                <span>хранить, сохранять, поддерживать</span></td>
        </tr>
        <tr>
            <td>
                know
            </td>
            <td>
                knew
            </td>
            <td>
                known
            </td>
            <td>
                <span>знать, иметь представление</span></td>
        </tr>
        <tr>
            <td>
                lay
            </td>
            <td>
                laid
            </td>
            <td>
                laid
            </td>
            <td>
                <span>класть, положить, покрывать</span></td>
        </tr>
        <tr>
            <td>
                lead
            </td>
            <td>
                led
            </td>
            <td>
                led
            </td>
            <td>
                <span>вести за собой, сопровождать, руководить</span></td>
        </tr>
        <tr>
            <td>
                leave
            </td>
            <td>
                left
            </td>
            <td>
                left
            </td>
            <td>
                <span>покидать, уходить, уезжать, оставлять</span></td>
        </tr>
        <tr>
            <td>
                lend
            </td>
            <td>
                lent
            </td>
            <td>
                lent
            </td>
            <td>
                <span>одалживать, давать взаймы (в долг)</span></td>
        </tr>
        <tr>
            <td>
                let
            </td>
            <td>
                let
            </td>
            <td>
                let
            </td>
            <td>
                <span>позволять, разрешать</span></td>
        </tr>
        <tr>
            <td>
                lie
            </td>
            <td>
                lay
            </td>
            <td>
                lain
            </td>
            <td>
                <span>лежать</span></td>
        </tr>
        <tr>
            <td>
                light
            </td>
            <td>
                lit
            </td>
            <td>
                lit
            </td>
            <td>
                <span>зажигать, светиться, освещать</span></td>
        </tr>
        <tr>
            <td>
                lose
            </td>
            <td>
                lost
            </td>
            <td>
                lost
            </td>
            <td>
                <span>терять, лишаться, утрачивать</span></td>
        </tr>
        <tr>
            <td>
                make
            </td>
            <td>
                made
            </td>
            <td>
                made
            </td>
            <td>
                <span>делать, создавать, изготавливать</span></td>
        </tr>
        <tr>
            <td>
                mean
            </td>
            <td>
                meant
            </td>
            <td>
                meant
            </td>
            <td>
                <span>значить, иметь в виду, подразумевать</span></td>
        </tr>
        <tr>
            <td>
                meet
            </td>
            <td>
                met
            </td>
            <td>
                met
            </td>
            <td>
                <span>встречать, знакомиться</span></td>
        </tr>
        <tr>
            <td>
                pay
            </td>
            <td>
                paid
            </td>
            <td>
                paid
            </td>
            <td>
                <span>платить, оплачивать, рассчитываться</span></td>
        </tr>
        <tr>
            <td>
                put
            </td>
            <td>
                put
            </td>
            <td>
                put
            </td>
            <td>
                <span>ставить, помещать, класть</span></td>
        </tr>
        <tr>
            <td>
                read
            </td>
            <td>
                read
            </td>
            <td>
                read
            </td>
            <td>
                <span>читать, прочитать</span></td>
        </tr>
        <tr>
            <td>
                ride
            </td>
            <td>
                rode
            </td>
            <td>
                ridden
            </td>
            <td>
                <span>ехать верхом, кататься</span></td>
        </tr>
        <tr>
            <td>
                ring
            </td>
            <td>
                rang
            </td>
            <td>
                rung
            </td>
            <td>
                <span>звенеть, звонить</span></td>
        </tr>
        <tr>
            <td>
                rise
            </td>
            <td>
                rose
            </td>
            <td>
                risen
            </td>
            <td>
                <span>восходить, вставать, подниматься</span></td>
        </tr>
        <tr>
            <td>
                run
            </td>
            <td>
                ran
            </td>
            <td>
                run
            </td>
            <td>
                <span>бежать, бегать</span></td>
        </tr>
        <tr>
            <td>
                say
            </td>
            <td>
                said
            </td>
            <td>
                said
            </td>
            <td>
                <span>говорить, сказать, произносить</span></td>
        </tr>
        <tr>
            <td>
                see
            </td>
            <td>
                saw
            </td>
            <td>
                seen
            </td>
            <td>
                <span>видеть</span></td>
        </tr>
        <tr>
            <td>
                seek
            </td>
            <td>
                sought
            </td>
            <td>
                sought
            </td>
            <td>
                <span>искать, разыскивать</span></td>
        </tr>
        <tr>
            <td>
                sell
            </td>
            <td>
                sold
            </td>
            <td>
                sold
            </td>
            <td>
                <span>продавать, торговать</span></td>
        </tr>
        <tr>
            <td>
                send
            </td>
            <td>
                sent
            </td>
            <td>
                sent
            </td>
            <td>
                <span>посылать, отправлять, отсылать</span></td>
        </tr>
        <tr>
            <td>
                set
            </td>
            <td>
                set
            </td>
            <td>
                set
            </td>
            <td>
                <span>устанавливать, задавать, назначать</span></td>
        </tr>
        <tr>
            <td>
                shake
            </td>
            <td>
                shook
            </td>
            <td>
                shaken
            </td>
            <td>
                <span>трясти, встряхивать</span></td>
        </tr>
        <tr>
            <td>
                shine
            </td>
            <td>
                shone
            </td>
            <td>
                shone
            </td>
            <td>
                <span>светить, сиять, озарять</span></td>
        </tr>
        <tr>
            <td>
                shoot
            </td>
            <td>
                shot
            </td>
            <td>
                shot
            </td>
            <td>
                <span>стрелять</span></td>
        </tr>
        <tr>
            <td>
                show
            </td>
            <td>
                showed
            </td>
            <td>
                shown, showed
            </td>
            <td>
                <span>показывать</span></td>
        </tr>
        <tr>
            <td>
                shut
            </td>
            <td>
                shut
            </td>
            <td>
                shut
            </td>
            <td>
                <span>закрывать, запирать, затворять</span></td>
        </tr>
        <tr>
            <td>
                sing
            </td>
            <td>
                sang
            </td>
            <td>
                sung
            </td>
            <td>
                <span>петь, напевать</span></td>
        </tr>
        <tr>
            <td>
                sink
            </td>
            <td>
                sank
            </td>
            <td>
                sunk
            </td>
            <td>
                <span>тонуть, погружаться</span></td>
        </tr>
        <tr>
            <td>
                sit
            </td>
            <td>
                sat
            </td>
            <td>
                sat
            </td>
            <td>
                <span>сидеть, садиться</span></td>
        </tr>
        <tr>
            <td>
                sleep
            </td>
            <td>
                slept
            </td>
            <td>
                slept
            </td>
            <td>
                <span>спать</span></td>
        </tr>
        <tr>
            <td>
                speak
            </td>
            <td>
                spoke
            </td>
            <td>
                spoken
            </td>
            <td>
                <span>говорить, разговаривать, высказываться</span></td>
        </tr>
        <tr>
            <td>
                spend
            </td>
            <td>
                spent
            </td>
            <td>
                spent
            </td>
            <td>
                <span>тратить, расходовать, проводить (время)</span></td>
        </tr>
        <tr>
            <td>
                stand
            </td>
            <td>
                stood
            </td>
            <td>
                stood
            </td>
            <td>
                <span>стоять</span></td>
        </tr>
        <tr>
            <td>
                steal
            </td>
            <td>
                stole
            </td>
            <td>
                stolen
            </td>
            <td>
                <span>воровать, красть</span></td>
        </tr>
        <tr>
            <td>
                stick
            </td>
            <td>
                stuck
            </td>
            <td>
                stuck
            </td>
            <td>
                <span>втыкать, приклеивать</span></td>
        </tr>
        <tr>
            <td>
                strike
            </td>
            <td>
                struck
            </td>
            <td>
                struck, stricken
            </td>
            <td>
                <span>ударять, бить, поражать</span></td>
        </tr>
        <tr>
            <td>
                swear
            </td>
            <td>
                swore
            </td>
            <td>
                sworn
            </td>
            <td>
                <span>клясться, присягать</span></td>
        </tr>
        <tr>
            <td>
                sweep
            </td>
            <td>
                swept
            </td>
            <td>
                swept
            </td>
            <td>
                <span>мести, подметать, смахивать</span></td>
        </tr>
        <tr>
            <td>
                swim
            </td>
            <td>
                swam
            </td>
            <td>
                swum
            </td>
            <td>
                <span>плавать, плыть</span></td>
        </tr>
        <tr>
            <td>
                swing
            </td>
            <td>
                swung
            </td>
            <td>
                swung
            </td>
            <td>
                <span>качаться, вертеться</span></td>
        </tr>
        <tr>
            <td>
                take
            </td>
            <td>
                took
            </td>
            <td>
                taken
            </td>
            <td>
                <span>брать, хватать, взять</span></td>
        </tr>
        <tr>
            <td>
                teach
            </td>
            <td>
                taught
            </td>
            <td>
                taught
            </td>
            <td>
                <span>учить, обучать</span></td>
        </tr>
        <tr>
            <td>
                tear
            </td>
            <td>
                tore
            </td>
            <td>
                torn
            </td>
            <td>
                <span>рвать, отрывать</span></td>
        </tr>
        <tr>
            <td>
                tell
            </td>
            <td>
                told
            </td>
            <td>
                told
            </td>
            <td>
                <span>рассказывать</span></td>
        </tr>
        <tr>
            <td>
                think
            </td>
            <td>
                thought
            </td>
            <td>
                thought
            </td>
            <td>
                <span>думать, мыслить, размышлять</span></td>
        </tr>
        <tr>
            <td>
                throw
            </td>
            <td>
                threw
            </td>
            <td>
                thrown
            </td>
            <td>
                <span>бросать, кидать, метать</span></td>
        </tr>
        <tr>
            <td>
                understand
            </td>
            <td>
                understood
            </td>
            <td>
                understood
            </td>
            <td>
                <span>понимать, постигать</span></td>
        </tr>
        <tr>
            <td>
                wake
            </td>
            <td>
                woke
            </td>
            <td>
                woken
            </td>
            <td>
                <span>просыпаться, будить</span></td>
        </tr>
        <tr>
            <td>
                wear
            </td>
            <td>
                wore
            </td>
            <td>
                worn
            </td>
            <td>
                <span>носить (одежду)</span></td>
        </tr>
        <tr>
            <td>
                win
            </td>
            <td>
                won
            </td>
            <td>
                won
            </td>
            <td>
                <span>победить, выиграть</span></td>
        </tr>
        <tr>
            <td>
                write
            </td>
            <td>
                wrote
            </td>
            <td>
                written
            </td>
            <td>
                <span>писать, записывать</span></td>
        </tr>
    </table>

</div>
</body>
</html>